# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-test-ci-cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d2585e5e8749449db285ee7d5583ceef }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e7db25be166e4f9187e4037a717ec5c6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_d2585e5e8749449db285ee7d5583ceef }}/test-ci-cd:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-test-ci-cd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_36469923fdc74e0f83c9bd09a83885b7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d2585e5e8749449db285ee7d5583ceef }}/maillotcedric/test-ci-cd:${{ github.sha }}'
